name: GitHub Actions Test
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Adding actions/checkout@v2
        uses: actions/checkout@v2
      - name: Append XML to history.json
        run: |
          python3 ${{ github.workspace }}/.github/workflows/append_to_history.py
      - name: Setup git - step 1
        run: git config --global user.email "adithraghavs@gmail.com"
      - name: Setup git - step 2
        run: git config --global user.name "Adith Raghav"
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "auto updating history.json"
      - name: Push to main
        run: git push