name: GitHub Actions Test
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Append to history.json
        uses: actions/checkout@v2
        run: |
          python3 ${{ github.workspace }}/append_to_history.py