name: GitHub Actions Test
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Adding actions/checkout@v2
        uses: actions/checkout@v2
      - name: Test
        run: git diff 7100c3bbc34a9667ca9034a8ec321677ed4b5828 4c5952b60b8a5911154534ea1fefec3567c49c52 ${{ github.workspace }}/data.xml
      - name: Run Python
        run: |
          python3 ${{ github.workspace }}/.github/workflows/app.py
      - name: Setup git - step 1
        run: git config --global user.email "adithraghavs@gmail.com"
      - name: Setup git - step 2
        run: git config --global user.name "Adith Raghav"
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "auto updating history.json and maybe checked for changes in data"
      - name: fetch from main 
        run: git fetch origin main
      - name: Push to main
        run: git push origin HEAD:main